networks:
  internal:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paias-server
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: paias-nginx
    restart: unless-stopped
    ports:
      - "7869:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal

  ollama-sandbox:
    image: ollama/ollama
    container_name: paias-ollama-sandbox
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "4g"
    read_only: true
    volumes:
      - ollama:/root/.ollama
    expose:
      - "7869"
    environment:
      - HTTP_PROXY=http://host.docker.internal:22225
      - HTTPS_PROXY=http://host.docker.internal:22225
      - NO_PROXY=localhost,127.0.0.1
    networks:
      - internal

  ollama-unsafe:
    image: ollama/ollama
    container_name: paias-ollama-unsafe
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "4g"
    network_mode: bridge
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:7868"

volumes:
  ollama:
