networks:
  internal:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paias-server
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - ollama-sandbox
      - ollama-unsafe
    networks:
      - internal

  ollama-sandbox:
    image: ollama/ollama
    container_name: paias-ollama-sandbox
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "4g"
    read_only: true
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
      - NO_PROXY=localhost,127.0.0.1
    networks:
      - internal
    cap_drop:
      - NET_ADMIN

  ollama-unsafe:
    image: ollama/ollama
    container_name: paias-ollama-unsafe
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "4g"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - internal

volumes:
  ollama:
