services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: paias-server
    ports:
      - "6969:6969"
    volumes:
      - ./server:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - ollama-sandbox
      - ollama-unsafe
      - searxng
      - redis
    networks:
      - paias

  ollama-sandbox:
    image: ollama/ollama
    container_name: paias-ollama-sandbox
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "6g"
    read_only: true
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11435
      - NO_PROXY=localhost,127.0.0.1
    networks:
      - paias
    cap_drop:
      - NET_ADMIN

  ollama-unsafe:
    image: ollama/ollama
    container_name: paias-ollama-unsafe
    restart: unless-stopped
    init: true
    deploy:
      resources:
        limits:
          memory: "6g"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - paias

  redis:
    container_name: paias-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - paias
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: paias-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - paias
    ports:
      - "8080:8080"
    volumes:
      - ./searxng-docker/searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-localhost}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  valkey-data2:
  searxng-data:
  ollama:

networks:
  paias:
    name: paias
    external: true
